-- 回滚列注释；恢复本迁移前已有的邮件字段注释。

-- 回滚同样强制在线 INPLACE DDL；拿不到元数据锁或不支持在线算法时直接失败。
SET SESSION lock_wait_timeout = 10;

ALTER TABLE accounts
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN farm_id BIGINT UNSIGNED NULL,
    MODIFY COLUMN account_type VARCHAR(16) NOT NULL,
    MODIFY COLUMN display_name VARCHAR(64) NOT NULL DEFAULT '',
    MODIFY COLUMN profile_json JSON NULL,
    MODIFY COLUMN row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    MODIFY COLUMN last_login_at DATETIME(3) NULL,
    MODIFY COLUMN deleted_at DATETIME(3) NULL,
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE sessions
    MODIFY COLUMN session_id BINARY(16) NOT NULL,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN device_id VARCHAR(128) NOT NULL,
    MODIFY COLUMN refresh_token_hash BINARY(32) NOT NULL DEFAULT '',
    MODIFY COLUMN status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN gateway_id VARCHAR(64) NULL,
    MODIFY COLUMN owner_epoch BIGINT UNSIGNED NOT NULL DEFAULT 1,
    MODIFY COLUMN current_farm_id BIGINT UNSIGNED NULL,
    MODIFY COLUMN last_client_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN last_server_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN last_acked_server_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN protocol_version VARCHAR(16) NOT NULL,
    MODIFY COLUMN expires_at DATETIME(3) NOT NULL,
    MODIFY COLUMN last_seen_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    MODIFY COLUMN revoked_at DATETIME(3) NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE wallets
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN coin_balance BIGINT NOT NULL DEFAULT 0,
    MODIFY COLUMN row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE farm_snapshots
    MODIFY COLUMN farm_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN snapshot JSON NOT NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    MODIFY COLUMN owner_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN last_event_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN route_epoch BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN actor_state VARCHAR(16) NOT NULL DEFAULT 'IDLE',
    MODIFY COLUMN schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    MODIFY COLUMN snapshot_checksum BINARY(32) NOT NULL DEFAULT '',
    MODIFY COLUMN next_pet_action_at DATETIME(3) NULL,
    MODIFY COLUMN checkpointed_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE cmd_receipts
    MODIFY COLUMN receipt_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN cmd_id VARCHAR(64) NOT NULL,
    MODIFY COLUMN result_code VARCHAR(48) NOT NULL,
    MODIFY COLUMN result_version BIGINT UNSIGNED NULL,
    MODIFY COLUMN response_digest VARBINARY(255) NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE outbox_events
    MODIFY COLUMN outbox_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL,
    MODIFY COLUMN aggregate_type VARCHAR(32) NOT NULL,
    MODIFY COLUMN aggregate_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN partition_key VARCHAR(64) NOT NULL,
    MODIFY COLUMN event_type VARCHAR(48) NOT NULL,
    MODIFY COLUMN schema_version VARCHAR(16) NOT NULL,
    MODIFY COLUMN payload JSON NOT NULL,
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    MODIFY COLUMN available_at DATETIME(3) NOT NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN headers_json JSON NULL,
    MODIFY COLUMN retry_count INT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN locked_by VARCHAR(64) NULL,
    MODIFY COLUMN locked_until DATETIME(3) NULL,
    MODIFY COLUMN published_at DATETIME(3) NULL,
    MODIFY COLUMN last_error VARCHAR(512) NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE auth_identities
    MODIFY COLUMN identity_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN provider VARCHAR(24) NOT NULL,
    MODIFY COLUMN provider_subject VARCHAR(191) NOT NULL,
    MODIFY COLUMN credential_hash VARBINARY(255) NULL,
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN verified_at DATETIME(3) NULL,
    MODIFY COLUMN deleted_at DATETIME(3) NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE inventory_items
    MODIFY COLUMN inventory_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN item_type VARCHAR(24) NOT NULL,
    MODIFY COLUMN item_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN quantity BIGINT NOT NULL DEFAULT 0,
    MODIFY COLUMN row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    MODIFY COLUMN deleted_at DATETIME(3) NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE economy_transactions
    MODIFY COLUMN transaction_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN biz_type VARCHAR(32) NOT NULL,
    MODIFY COLUMN biz_id BINARY(16) NOT NULL,
    MODIFY COLUMN currency_type VARCHAR(16) NOT NULL DEFAULT 'COIN',
    MODIFY COLUMN balance_before BIGINT NOT NULL,
    MODIFY COLUMN balance_delta BIGINT NOT NULL,
    MODIFY COLUMN balance_after BIGINT NOT NULL,
    MODIFY COLUMN item_changes_json JSON NULL,
    MODIFY COLUMN source_type VARCHAR(32) NOT NULL,
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'COMMITTED',
    MODIFY COLUMN trace_id VARCHAR(64) NULL,
    MODIFY COLUMN metadata_json JSON NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE consumed_events
    MODIFY COLUMN consumed_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL,
    MODIFY COLUMN consumer_name VARCHAR(64) NOT NULL,
    MODIFY COLUMN processed_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE friendships
    MODIFY COLUMN friendship_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id_a BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN user_id_b BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE mails
    MODIFY COLUMN mail_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN sender_id BIGINT UNSIGNED NULL COMMENT '发件人 user_id；NULL 表示系统邮件',
    MODIFY COLUMN mail_type VARCHAR(32) NOT NULL COMMENT 'FRIEND_ACCEPTED|STEAL_NOTIFY|SYSTEM',
    MODIFY COLUMN title VARCHAR(128) NOT NULL,
    MODIFY COLUMN content VARCHAR(512) NOT NULL DEFAULT '',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'UNREAD' COMMENT 'UNREAD|READ|DELETED',
    MODIFY COLUMN read_at DATETIME(3) NULL,
    MODIFY COLUMN expires_at DATETIME(3) NULL,
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE mail_attachments
    MODIFY COLUMN attachment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN mail_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN item_type VARCHAR(16) NOT NULL COMMENT 'CROP|SEED|COIN',
    MODIFY COLUMN item_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'COIN 时为 0',
    MODIFY COLUMN quantity BIGINT UNSIGNED NOT NULL DEFAULT 1,
    MODIFY COLUMN claimed_at DATETIME(3) NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE player_tasks
    MODIFY COLUMN task_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN task_key VARCHAR(64) NOT NULL,
    MODIFY COLUMN progress INT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL,
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE catalog_unlocks
    MODIFY COLUMN unlock_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN catalog_key VARCHAR(64) NOT NULL,
    MODIFY COLUMN unlocked_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE player_pets
    MODIFY COLUMN pet_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
    MODIFY COLUMN pet_type VARCHAR(32) NOT NULL DEFAULT 'CHICKEN',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN auto_harvest_enabled TINYINT(1) NOT NULL DEFAULT 1,
    MODIFY COLUMN purchased_at DATETIME(3) NOT NULL,
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE consumer_failed_events
    MODIFY COLUMN failure_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN consumer_group VARCHAR(255) NOT NULL,
    MODIFY COLUMN consumer_name VARCHAR(128) NOT NULL,
    MODIFY COLUMN topic VARCHAR(255) NOT NULL,
    MODIFY COLUMN partition_id INT NOT NULL,
    MODIFY COLUMN message_offset BIGINT NOT NULL,
    MODIFY COLUMN message_key LONGBLOB NULL,
    MODIFY COLUMN event_id VARCHAR(128) NULL,
    MODIFY COLUMN payload LONGBLOB NOT NULL,
    MODIFY COLUMN attempt_count INT UNSIGNED NOT NULL,
    MODIFY COLUMN last_error VARCHAR(2048) NOT NULL,
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    MODIFY COLUMN first_failed_at DATETIME(3) NOT NULL,
    MODIFY COLUMN last_failed_at DATETIME(3) NOT NULL,
    MODIFY COLUMN resolved_at DATETIME(3) NULL,
    ALGORITHM=INPLACE, LOCK=NONE;
