-- 为当前业务 schema 的每个字段补充数据字典注释。
-- 仅修改列元数据，不改变列类型、默认值、约束或索引。
-- 强制使用在线 INPLACE DDL 并允许并发读写；不支持时直接失败，禁止回退为 COPY 重建表。
SET SESSION lock_wait_timeout = 10;

ALTER TABLE accounts
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '玩家账号唯一标识',
    MODIFY COLUMN farm_id BIGINT UNSIGNED NULL COMMENT '关联农场标识；创建农场前可为空',
    MODIFY COLUMN account_type VARCHAR(16) NOT NULL COMMENT '账号类型：GUEST 或 REGISTERED',
    MODIFY COLUMN display_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '玩家展示名称',
    MODIFY COLUMN profile_json JSON NULL COMMENT '玩家扩展资料 JSON',
    MODIFY COLUMN row_version BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '账号乐观锁版本号',
    MODIFY COLUMN last_login_at DATETIME(3) NULL COMMENT '最近一次登录时间',
    MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '软删除时间；为空表示未删除',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '账号状态：ACTIVE、BANNED 或 DELETED',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '账号创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '账号最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE sessions
    MODIFY COLUMN session_id BINARY(16) NOT NULL COMMENT '会话唯一标识（16 字节二进制）',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家账号标识',
    MODIFY COLUMN device_id VARCHAR(128) NOT NULL COMMENT '客户端设备标识',
    MODIFY COLUMN refresh_token_hash BINARY(32) NOT NULL DEFAULT '' COMMENT '刷新令牌哈希值',
    MODIFY COLUMN status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE' COMMENT '会话状态：ACTIVE、HANDOFF_PENDING、REVOKED 或 EXPIRED',
    MODIFY COLUMN gateway_id VARCHAR(64) NULL COMMENT '当前会话归属网关实例标识',
    MODIFY COLUMN owner_epoch BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '会话归属纪元，用于迁移隔离',
    MODIFY COLUMN current_farm_id BIGINT UNSIGNED NULL COMMENT '当前访问或操作的农场标识',
    MODIFY COLUMN last_client_seq BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后处理的客户端消息序号',
    MODIFY COLUMN last_server_seq BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后发送的服务端消息序号',
    MODIFY COLUMN last_acked_server_seq BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '客户端最后确认的服务端消息序号',
    MODIFY COLUMN protocol_version VARCHAR(16) NOT NULL COMMENT '客户端协议版本',
    MODIFY COLUMN expires_at DATETIME(3) NOT NULL COMMENT '会话过期时间',
    MODIFY COLUMN last_seen_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '最近一次活跃时间',
    MODIFY COLUMN revoked_at DATETIME(3) NULL COMMENT '会话撤销时间；为空表示未撤销',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '会话创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '会话最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE wallets
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家账号标识',
    MODIFY COLUMN coin_balance BIGINT NOT NULL DEFAULT 0 COMMENT '当前金币余额',
    MODIFY COLUMN row_version BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '钱包乐观锁版本号',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '钱包创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '钱包最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE farm_snapshots
    MODIFY COLUMN farm_id BIGINT UNSIGNED NOT NULL COMMENT '农场唯一标识',
    MODIFY COLUMN version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '农场状态版本号',
    MODIFY COLUMN snapshot JSON NOT NULL COMMENT '农场权威状态快照 JSON',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '快照创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '快照最近更新时间',
    MODIFY COLUMN owner_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '农场所属玩家账号标识',
    MODIFY COLUMN last_event_seq BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已应用的最后一个农场事件序号',
    MODIFY COLUMN route_epoch BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '农场 Actor 路由纪元',
    MODIFY COLUMN actor_state VARCHAR(16) NOT NULL DEFAULT 'IDLE' COMMENT '农场 Actor 状态：IDLE、READY 或 MIGRATING',
    MODIFY COLUMN schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '快照 JSON schema 版本',
    MODIFY COLUMN snapshot_checksum BINARY(32) NOT NULL DEFAULT '' COMMENT '快照内容校验和',
    MODIFY COLUMN next_pet_action_at DATETIME(3) NULL COMMENT '下一次宠物自动操作时间',
    MODIFY COLUMN checkpointed_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '最近一次持久化检查点时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE cmd_receipts
    MODIFY COLUMN receipt_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '命令回执唯一标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '发起命令的玩家账号标识',
    MODIFY COLUMN cmd_id VARCHAR(64) NOT NULL COMMENT '客户端命令幂等标识',
    MODIFY COLUMN result_code VARCHAR(48) NOT NULL COMMENT '命令处理结果代码',
    MODIFY COLUMN result_version BIGINT UNSIGNED NULL COMMENT '命令成功后的状态版本号',
    MODIFY COLUMN response_digest VARBINARY(255) NULL COMMENT '命令响应内容摘要',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '回执创建时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE outbox_events
    MODIFY COLUMN outbox_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Outbox 事件自增标识',
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL COMMENT '业务事件全局唯一标识',
    MODIFY COLUMN aggregate_type VARCHAR(32) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN aggregate_id BIGINT UNSIGNED NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN partition_key VARCHAR(64) NOT NULL COMMENT '消息分区键',
    MODIFY COLUMN event_type VARCHAR(48) NOT NULL COMMENT '业务事件类型',
    MODIFY COLUMN schema_version VARCHAR(16) NOT NULL COMMENT '事件载荷 schema 版本',
    MODIFY COLUMN payload JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '投递状态：PENDING、PUBLISHING、PUBLISHED 或 DEAD',
    MODIFY COLUMN available_at DATETIME(3) NOT NULL COMMENT '事件可被投递的最早时间',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '事件写入 Outbox 的时间',
    MODIFY COLUMN headers_json JSON NULL COMMENT '消息头 JSON',
    MODIFY COLUMN retry_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '投递重试次数',
    MODIFY COLUMN locked_by VARCHAR(64) NULL COMMENT '当前投递锁持有者实例标识',
    MODIFY COLUMN locked_until DATETIME(3) NULL COMMENT '投递锁失效时间',
    MODIFY COLUMN published_at DATETIME(3) NULL COMMENT '成功发布到消息系统的时间',
    MODIFY COLUMN last_error VARCHAR(512) NULL COMMENT '最近一次投递失败原因',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '事件最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE auth_identities
    MODIFY COLUMN identity_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '认证身份自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '关联玩家账号标识',
    MODIFY COLUMN provider VARCHAR(24) NOT NULL COMMENT '认证提供方',
    MODIFY COLUMN provider_subject VARCHAR(191) NOT NULL COMMENT '认证提供方中的主体唯一标识',
    MODIFY COLUMN credential_hash VARBINARY(255) NULL COMMENT '认证凭据哈希值',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '认证身份状态：ACTIVE 或 REVOKED',
    MODIFY COLUMN verified_at DATETIME(3) NULL COMMENT '认证身份验证完成时间',
    MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '认证身份软删除时间',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '认证身份创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '认证身份最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE inventory_items
    MODIFY COLUMN inventory_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '库存记录自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家账号标识',
    MODIFY COLUMN item_type VARCHAR(24) NOT NULL COMMENT '物品类别，例如 CROP 或 SEED',
    MODIFY COLUMN item_id BIGINT UNSIGNED NOT NULL COMMENT '物品配置标识',
    MODIFY COLUMN quantity BIGINT NOT NULL DEFAULT 0 COMMENT '当前物品数量',
    MODIFY COLUMN row_version BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '库存乐观锁版本号',
    MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '库存记录软删除时间',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '库存记录创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '库存记录最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE economy_transactions
    MODIFY COLUMN transaction_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '经济流水自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '发生经济变动的玩家账号标识',
    MODIFY COLUMN biz_type VARCHAR(32) NOT NULL COMMENT '业务类型，用于幂等去重',
    MODIFY COLUMN biz_id BINARY(16) NOT NULL COMMENT '业务幂等标识（16 字节二进制）',
    MODIFY COLUMN currency_type VARCHAR(16) NOT NULL DEFAULT 'COIN' COMMENT '货币类型，当前为 COIN',
    MODIFY COLUMN balance_before BIGINT NOT NULL COMMENT '变动前余额',
    MODIFY COLUMN balance_delta BIGINT NOT NULL COMMENT '余额变动值；正数入账，负数扣减',
    MODIFY COLUMN balance_after BIGINT NOT NULL COMMENT '变动后余额',
    MODIFY COLUMN item_changes_json JSON NULL COMMENT '关联库存变动明细 JSON',
    MODIFY COLUMN source_type VARCHAR(32) NOT NULL COMMENT '流水来源类型',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'COMMITTED' COMMENT '流水状态：COMMITTED 或 REVERSED',
    MODIFY COLUMN trace_id VARCHAR(64) NULL COMMENT '请求链路追踪标识',
    MODIFY COLUMN metadata_json JSON NULL COMMENT '扩展业务元数据 JSON',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '经济流水创建时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE consumed_events
    MODIFY COLUMN consumed_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '消费去重记录自增标识',
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL COMMENT '已消费业务事件标识',
    MODIFY COLUMN consumer_name VARCHAR(64) NOT NULL COMMENT '消费者名称',
    MODIFY COLUMN processed_at DATETIME(3) NOT NULL COMMENT '事件处理完成时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE friendships
    MODIFY COLUMN friendship_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '好友关系自增标识',
    MODIFY COLUMN user_id_a BIGINT UNSIGNED NOT NULL COMMENT '较小的好友玩家账号标识',
    MODIFY COLUMN user_id_b BIGINT UNSIGNED NOT NULL COMMENT '较大的好友玩家账号标识',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '好友关系创建时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE mails
    MODIFY COLUMN mail_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '站内信自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '收件玩家账号标识',
    MODIFY COLUMN sender_id BIGINT UNSIGNED NULL COMMENT '发件人 user_id；NULL 表示系统邮件',
    MODIFY COLUMN mail_type VARCHAR(32) NOT NULL COMMENT 'FRIEND_ACCEPTED|STEAL_NOTIFY|SYSTEM',
    MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '邮件标题',
    MODIFY COLUMN content VARCHAR(512) NOT NULL DEFAULT '' COMMENT '邮件正文',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'UNREAD' COMMENT 'UNREAD|READ|DELETED',
    MODIFY COLUMN read_at DATETIME(3) NULL COMMENT '邮件阅读时间',
    MODIFY COLUMN expires_at DATETIME(3) NULL COMMENT '邮件过期时间',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '邮件创建时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE mail_attachments
    MODIFY COLUMN attachment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邮件附件自增标识',
    MODIFY COLUMN mail_id BIGINT UNSIGNED NOT NULL COMMENT '所属邮件标识',
    MODIFY COLUMN item_type VARCHAR(16) NOT NULL COMMENT 'CROP|SEED|COIN',
    MODIFY COLUMN item_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'COIN 时为 0',
    MODIFY COLUMN quantity BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '附件物品数量',
    MODIFY COLUMN claimed_at DATETIME(3) NULL COMMENT '附件领取时间；为空表示未领取',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE player_tasks
    MODIFY COLUMN task_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '玩家任务自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家账号标识',
    MODIFY COLUMN task_key VARCHAR(64) NOT NULL COMMENT '任务配置键',
    MODIFY COLUMN progress INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前任务进度',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '任务状态：ACTIVE、COMPLETED 或 REWARD_CLAIMED',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '任务创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '任务最近更新时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE catalog_unlocks
    MODIFY COLUMN unlock_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图鉴解锁记录自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家账号标识',
    MODIFY COLUMN catalog_key VARCHAR(64) NOT NULL COMMENT '图鉴条目配置键',
    MODIFY COLUMN unlocked_at DATETIME(3) NOT NULL COMMENT '图鉴解锁时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE player_pets
    MODIFY COLUMN pet_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '玩家宠物自增标识',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '所属玩家账号标识',
    MODIFY COLUMN pet_type VARCHAR(32) NOT NULL DEFAULT 'CHICKEN' COMMENT '宠物类型',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '宠物状态：ACTIVE 或 INACTIVE',
    MODIFY COLUMN auto_harvest_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用宠物自动收获：1 启用，0 停用',
    MODIFY COLUMN purchased_at DATETIME(3) NOT NULL COMMENT '宠物购买时间',
    ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE consumer_failed_events
    MODIFY COLUMN failure_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '失败消费记录自增标识',
    MODIFY COLUMN consumer_group VARCHAR(255) NOT NULL COMMENT 'Kafka 消费者组名称',
    MODIFY COLUMN consumer_name VARCHAR(128) NOT NULL COMMENT '消费者实例或处理器名称',
    MODIFY COLUMN topic VARCHAR(255) NOT NULL COMMENT 'Kafka 主题名称',
    MODIFY COLUMN partition_id INT NOT NULL COMMENT 'Kafka 分区编号',
    MODIFY COLUMN message_offset BIGINT NOT NULL COMMENT 'Kafka 消息位点',
    MODIFY COLUMN message_key LONGBLOB NULL COMMENT 'Kafka 消息键原始字节',
    MODIFY COLUMN event_id VARCHAR(128) NULL COMMENT '事件标识；无法解析时为空',
    MODIFY COLUMN payload LONGBLOB NOT NULL COMMENT '失败消息原始载荷',
    MODIFY COLUMN attempt_count INT UNSIGNED NOT NULL COMMENT '处理尝试次数',
    MODIFY COLUMN last_error VARCHAR(2048) NOT NULL COMMENT '最近一次处理失败原因',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '失败消息状态：PENDING、REPLAYED 或 IGNORED',
    MODIFY COLUMN first_failed_at DATETIME(3) NOT NULL COMMENT '首次处理失败时间',
    MODIFY COLUMN last_failed_at DATETIME(3) NOT NULL COMMENT '最近一次处理失败时间',
    MODIFY COLUMN resolved_at DATETIME(3) NULL COMMENT '失败消息处置完成时间',
    ALGORITHM=INPLACE, LOCK=NONE;
